#!/usr/bin/env python3
# Generates the root + member deno.json for running twenty-server's source on Deno.
# Run AFTER prepare-deno-deps.sh (needs node_modules to auto-resolve deep subpaths).
#
# Root deno.json: workspace + nodeModulesDir + import map for (a) deps the source
# imports but Deno can't resolve from a package scope (react/esbuild/... — undeclared
# or externalized-from-built-workspace-packages), (b) the lingui macro runtime shim
# (pure-Deno replacement for the build-time macro), (c) auto-discovered deep npm
# subpaths that lack a file extension (typeorm/graphql/@nestjs internals).
# Member deno.json: the `src/` path alias + node-builtin specifiers mapped to `node:`.
import json, re, glob, os

NM = 'node_modules/.deno'

def find_pkg_dir(pkg):
    hits = sorted(glob.glob(f'{NM}/{pkg.replace("/", "+")}@*/node_modules/{pkg}'))
    if not hits: return None, None
    d = hits[0]
    m = re.search(rf'{re.escape(pkg.replace("/", "+"))}@([^/]+)/', d)
    return d, (m.group(1) if m else None)

def pkgname(spec):
    p = spec.split('/'); return '/'.join(p[:2]) if spec.startswith('@') else p[0]

deep = set()
for f in glob.glob('packages/twenty-server/src/**/*.ts', recursive=True):
    if f.endswith('.spec.ts') or '__tests__' in f: continue
    try: txt = open(f).read()
    except: continue
    for m in re.finditer(r"""from\s*['"]([^'".][^'"]*)['"]""", txt):
        s = m.group(1)
        if s.startswith('node:') or s.startswith('src/') or s.startswith('twenty-'): continue
        if '/' in s and not (s.startswith('@') and s.count('/') == 1):
            deep.add(s)

deep_map = {}
for spec in sorted(deep):
    name = pkgname(spec); pdir, ver = find_pkg_dir(name)
    if not pdir or not ver: continue
    rel = spec[len(name)+1:]
    for c in (f'{rel}.mjs', f'{rel}.js', f'{rel}/index.mjs', f'{rel}/index.js'):
        if os.path.isfile(f'{pdir}/{c}'):
            # Map to the node_modules FILE PATH (same package instance as the bare
            # `import 'pkg'`), NOT an `npm:` specifier — npm: spins up a SEPARATE
            # instance, splitting singleton state (TypeMetadataStorage, typeorm/Nest
            # metadata storages) and causing duplicate GraphQL types / lost metadata.
            deep_map[spec] = f'./{pdir}/{c}'; break

imports = {
  'react': 'npm:react@18.3.1',
  'react/jsx-runtime': 'npm:react@18.3.1/jsx-runtime',
  '@lingui/message-utils/compileMessage': 'npm:@lingui/message-utils@5.9.5/compileMessage',
  '@lingui/core': 'npm:@lingui/core@5.9.5',
  '@lingui/core/macro': './deno-spike/shims/lingui-macro.ts',
  '@lingui/react/macro': './deno-spike/shims/lingui-macro.ts',
  'esbuild': 'npm:esbuild@0.25.12',
  'graphql-type-json': './deno-spike/shims/graphql-type-json.ts',
  '@tiptap/core': 'npm:@tiptap/core@3.26.0',
  'p-limit': 'npm:p-limit@2.3.0',
  'qs': 'npm:qs@6.14.2',
}

# Cloud SDK + heavy-but-unused dependencies that bloat the runtime memory
# footprint on Deno Deploy isolates. In deno-mode (PG queue/cache/sessions/
# pub-sub, local file storage, etc.) Twenty never actually calls into these,
# but the source has `import { S3Client } from '@aws-sdk/client-s3'` etc.,
# and NestJS DI constructs every service in the graph at boot — those
# constructors `new` the SDK clients, which would normally drag in 50-150 MB
# of npm code apiece. Map each to a non-throwing Proxy stub: construction
# succeeds (NestJS DI happy), accessing properties returns more stubs, and
# only a method CALL throws — which never happens unless the cloud feature
# is actually enabled via config (FILE_STORAGE_TYPE, EMAIL_DRIVER, …).
# Each cloud SDK maps to its OWN per-package shim. The shims live in
# deno-spike/shims/cloud/ and were generated by /tmp/gen-stubs.py — they
# re-export every name twenty-server actually imports from that package
# as the same non-throwing Proxy. Per-package files are required (not a
# single shared stub) because Deno's strict ESM checks named exports at
# parse time, and dynamic Proxy properties don't show up as static exports.
CLOUD_STUBS = {
  '@aws-sdk/client-lambda':         './deno-spike/shims/cloud/aws-sdk__client-lambda.ts',
  '@aws-sdk/client-s3':             './deno-spike/shims/cloud/aws-sdk__client-s3.ts',
  '@aws-sdk/client-sesv2':          './deno-spike/shims/cloud/aws-sdk__client-sesv2.ts',
  '@aws-sdk/client-sts':            './deno-spike/shims/cloud/aws-sdk__client-sts.ts',
  '@aws-sdk/credential-providers':  './deno-spike/shims/cloud/aws-sdk__credential-providers.ts',
  '@aws-sdk/s3-request-presigner':  './deno-spike/shims/cloud/aws-sdk__s3-request-presigner.ts',
  '@azure/msal-node':               './deno-spike/shims/cloud/azure__msal-node.ts',
  '@microsoft/microsoft-graph-client': './deno-spike/shims/cloud/microsoft__microsoft-graph-client.ts',
  '@microsoft/microsoft-graph-types':  './deno-spike/shims/cloud/microsoft__microsoft-graph-types.ts',
  '@jrmdayn/googleapis-batcher':    './deno-spike/shims/cloud/jrmdayn__googleapis-batcher.ts',
  'googleapis':                     './deno-spike/shims/cloud/googleapis.ts',
  'cloudflare':                     './deno-spike/shims/cloud/cloudflare.ts',
  'cloudflare/core':                './deno-spike/shims/cloud/cloudflare__core.ts',
}
imports.update(CLOUD_STUBS)
imports = {**deep_map, **imports}  # manual mappings win (e.g. lingui macro shim)
# Tasks define the end-to-end Deno-only workflow. Each shells out to either an
# in-repo script or a node-tool binary from node_modules/.bin — no yarn, no nx.
tasks = {
  'prepare': 'bash deno-spike/prepare-deno-deps.sh',
  'apply-patches': 'bash deno-spike/apply-patches.sh ./ node_modules',
  'build:front': 'bash deno-spike/build-frontend.sh',
  # Full one-shot bootstrap: install + scaffold + patch + build the frontend.
  # Named `build:all` (not `build`) to avoid being shadowed by twenty-front's
  # own `build` script in its package.json, which Deno auto-exposes as a task.
  'build:all': 'deno task prepare && deno task apply-patches && deno task build:front',
  # DB setup + migrations (read PG_DATABASE_URL etc. from the environment).
  'db:setup': 'cd packages/twenty-server && deno run -A --sloppy-imports boot-setup-db.ts',
  'db:migrate': 'cd packages/twenty-server && deno run -A --sloppy-imports boot-migrate.ts',
  # The unified API + Deno.cron entrypoint.
  'serve': 'cd packages/twenty-server && deno run -A --unstable-cron --sloppy-imports boot-serve.ts',
}
# Workspace list matches prepare-deno-deps.sh's SERVER_WORKSPACES. Frontend
# packages are runtime-unused (pre-built bundle ships in twenty-server/src/front)
# and skipping them speeds up `deno install` + Deploy's module materialization.
_ws = ['./packages/twenty-server','./packages/twenty-shared','./packages/twenty-emails','./packages/twenty-client-sdk']
if os.environ.get('DEPLOY_INCLUDE_FRONTEND') == '1':
    _ws += ['./packages/twenty-front','./packages/twenty-ui','./packages/twenty-front-component-renderer']
root = {
  'nodeModulesDir': 'auto',
  'workspace': _ws,
  # sloppy-imports applies to every entrypoint Deno resolves under this project.
  # Member deno.json may only narrow flags, not introduce ones the root rejects,
  # so the runtime needs them declared here too.
  'unstable': ['sloppy-imports', 'cron'],
  'tasks': tasks,
  'imports': imports,
}
json.dump(root, open('deno.json', 'w'), indent=2)

builtins = ['assert','assert/strict','buffer','child_process','cluster','console','constants','crypto','dgram','diagnostics_channel','dns','dns/promises','domain','events','fs','fs/promises','http','http2','https','inspector','inspector/promises','module','net','os','path','path/posix','path/win32','perf_hooks','process','punycode','querystring','readline','readline/promises','repl','stream','stream/consumers','stream/promises','stream/web','string_decoder','sys','timers','timers/promises','tls','trace_events','tty','url','util','util/types','v8','vm','wasi','worker_threads','zlib','async_hooks']
# `unstable` is set on the ROOT deno.json only — Deno warns that the field
# "can only be specified in the workspace root deno.json file" and ignores
# member-level declarations.
member = {'compilerOptions': {'experimentalDecorators': True, 'emitDecoratorMetadata': True},
          'imports': {'src/': './src/', **{b: f'node:{b}' for b in builtins}}}
json.dump(member, open('packages/twenty-server/deno.json', 'w'), indent=2)
print(f"wrote deno.json (root: {len(imports)} imports incl {len(deep_map)} deep) + member")
