#!/usr/bin/env bash
# Prepares the repo so `deno install` can resolve twenty-server's full npm dependency
# graph (the foundation for booting the real server on Deno). Two transforms are
# needed because Deno doesn't speak Yarn's dialect:
#
#   1. Scope `workspaces` to the server-needed packages. Deno walks every workspace
#      member, and twenty-front pulls `linkify-react@4.3.3`, whose published manifest
#      has a malformed requirement (`linkifyjs: "==4.3.3"`) that Deno's semver parser
#      rejects, aborting the whole install. The server doesn't use twenty-front.
#   2. Rewrite Yarn `patch:NAME@VER#file` specs to the exact `VER`. Deno can't parse
#      the `patch:` protocol; left as-is it resolves the wrong versions. After install
#      we re-apply the patches with apply-patches.sh (which needs the exact versions).
#
# This MUTATES package.json + packages/twenty-server/package.json (backed up to
# /tmp). It intentionally leaves them transformed so `deno run`/deploy also resolve
# the scoped graph — that is "deno build mode". Revert with:
#   git checkout package.json packages/twenty-server/package.json
#
# Known limitation: Deno ignores yarn.lock, so `^x-dev` ranges drift (e.g.
# @typescript/native-preview / tsgo resolves newer and breaks the nx BUILD toolchain).
# That only affects nx-based typecheck/test, not running the app — pin exact versions
# if you need the nx toolchain under Deno.
#
#   bash deno-spike/prepare-deno-deps.sh && bash deno-spike/apply-patches.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

cp package.json /tmp/twenty-root-package.json.deno-bak
cp packages/twenty-server/package.json /tmp/twenty-server-package.json.deno-bak
echo "backed up package.json files to /tmp/*.deno-bak"

python3 - <<'PY'
import json, re

import os as _os
# Runtime-needed workspace packages. On Deno Deploy where the frontend bundle
# ships pre-built in packages/twenty-server/src/front, the frontend packages
# (twenty-front, twenty-ui, twenty-front-component-renderer) aren't imported
# by the server at runtime and shouldn't slow down `deno install` or Deploy's
# module materialization. Local frontend rebuilds (FORCE_FRONTEND_REBUILD=1)
# need them — opt in with DEPLOY_INCLUDE_FRONTEND=1.
SERVER_WORKSPACES = [
    'packages/twenty-server',
    'packages/twenty-shared',
    'packages/twenty-emails',
    'packages/twenty-client-sdk',
]
if _os.environ.get('DEPLOY_INCLUDE_FRONTEND') == '1':
    SERVER_WORKSPACES += [
        'packages/twenty-front',
        'packages/twenty-ui',
        'packages/twenty-front-component-renderer',
    ]

def depatch(deps):
    for name, spec in list(deps.items()):
        if isinstance(spec, str) and spec.startswith('patch:'):
            # Two shapes seen in this repo:
            #   patch:<name>@<ver>#<file>            (root/server)
            #   patch:<name>@npm%3A<ver>#<file>      (twenty-front)
            match = re.search(r'(?:@npm%3A|@)([0-9][^@#]*)#', spec)
            if match:
                deps[name] = match.group(1)
                print(f'  de-patched {name}: -> {match.group(1)}')

root = json.load(open('package.json'))
root['workspaces'] = {'packages': SERVER_WORKSPACES}
for section in ('dependencies', 'devDependencies'):
    depatch(root.get(section, {}))
json.dump(root, open('package.json', 'w'), indent=2)
print('scoped workspaces ->', SERVER_WORKSPACES)

# De-patch every scoped workspace member, not just the server. twenty-front pulls
# react-phone-number-input via `patch:` too; leaving it as `patch:` makes Deno
# resolve nothing for it, and Rollup can't find the package at build time.
for ws in SERVER_WORKSPACES:
    pkg_path = f'{ws}/package.json'
    try:
        pkg = json.load(open(pkg_path))
    except FileNotFoundError:
        continue
    for section in ('dependencies', 'devDependencies'):
        depatch(pkg.get(section, {}))
    json.dump(pkg, open(pkg_path, 'w'), indent=2)
PY

# Minimal ROOT deno.json so `deno install` links the workspace members (twenty-shared
# etc.). nodeModulesDir must live in the root deno.json (Deno warns on a member). The
# full import map is generated by gen-import-map.py AFTER install (it scans node_modules
# to auto-resolve extensionless deep subpaths). Workspace list is derived from the
# SERVER_WORKSPACES list above (Python printed it to /tmp/ws-list for shell to read).
python3 -c "
import json, os
ws = ['packages/twenty-server','packages/twenty-shared','packages/twenty-emails','packages/twenty-client-sdk']
if os.environ.get('DEPLOY_INCLUDE_FRONTEND') == '1':
    ws += ['packages/twenty-front','packages/twenty-ui','packages/twenty-front-component-renderer']
json.dump({'nodeModulesDir':'auto','workspace':[f'./{p}' for p in ws]}, open('deno.json','w'), indent=2)
open('/tmp/ws-list','w').write(' '.join(p.split('/')[-1] for p in ws if p != 'packages/twenty-server'))
print('initial deno.json: workspace =', ws)
"

# Production-only mode on Deno Deploy: strip devDependencies from every
# scoped package.json before `deno install`. jest/eslint/swc-cli/lingui-cli
# etc. aren't imported at runtime and their transitive trees would burn
# Deploy's 5-min build cap during the `deploying` step. `deno install --prod`
# isn't available on Deploy's Deno version, so we mutate manifests instead.
# Local rebuilds (DEPLOY_INCLUDE_FRONTEND=1) skip this so vite/tsc stay.
if [ "${DEPLOY_INCLUDE_FRONTEND:-0}" != "1" ]; then
  python3 - <<'PY'
import json
for p in ['package.json','packages/twenty-server/package.json',
          'packages/twenty-shared/package.json','packages/twenty-emails/package.json',
          'packages/twenty-client-sdk/package.json']:
  try:
    j = json.load(open(p))
  except FileNotFoundError:
    continue
  if 'devDependencies' in j:
    n = len(j['devDependencies']); del j['devDependencies']
    json.dump(j, open(p,'w'), indent=2)
    print(f'  stripped {n} devDeps from {p}')
PY
fi

echo "running deno install ..."
deno install

# Node-style workspace symlinks. Deno's node_modules layout resolves workspace members
# its own way, but Node-based build tools (vite) need real node_modules/<pkg> symlinks
# (which Yarn would create). Without these, building twenty-emails fails on
# `Cannot find module 'twenty-shared/translations'`.
for pkg in $(cat /tmp/ws-list); do
  ln -sfn "../packages/$pkg" "node_modules/$pkg"
done

# Yarn-style flat hoisting: every package Deno installed into `.deno/<pkg>@<ver>/`
# gets a top-level `node_modules/<pkg>` symlink IF none already exists. Node-based
# build tools (vite, rollup) walk up `node_modules` looking for transitive deps;
# Deno's nested layout hides them. This makes the layout look like what yarn's
# nodeLinker: node-modules produces, without requiring yarn. First wins on
# version conflicts — fine for build tooling, which doesn't care about version
# diversity at this level.
python3 - <<'PY'
import os
linked = 0
for d in sorted(os.listdir('node_modules/.deno')):
    p = f'node_modules/.deno/{d}/node_modules'
    if not os.path.isdir(p):
        continue
    for entry in os.listdir(p):
        if entry.startswith('.'):
            continue
        if entry.startswith('@'):
            scope_dir = f'{p}/{entry}'
            if not os.path.isdir(scope_dir):
                continue
            for sub in os.listdir(scope_dir):
                # symlink lives at node_modules/<scope>/<sub>. The target is
                # resolved from node_modules/<scope>/, so escape ONE level back
                # to node_modules/ and then descend into .deno/.
                src = f'../.deno/{d}/node_modules/{entry}/{sub}'
                dst = f'node_modules/{entry}/{sub}'
                if os.path.lexists(dst):
                    continue
                os.makedirs(f'node_modules/{entry}', exist_ok=True)
                os.symlink(src, dst); linked += 1
        else:
            # symlink lives at node_modules/<pkg>, target is relative to node_modules/.
            src = f'.deno/{d}/node_modules/{entry}'
            dst = f'node_modules/{entry}'
            if os.path.lexists(dst):
                continue
            os.symlink(src, dst); linked += 1
print(f'flat-hoisted {linked} package(s) to node_modules/')
PY

# Build the workspace packages that consumers resolve only via dist/ (their package
# exports point at dist). Runtime .mjs comes from vite; the tsgo .d.ts step may fail on
# the drifted toolchain but that's types-only and irrelevant to running the app.
for pkg in twenty-shared twenty-emails twenty-client-sdk; do
  if [ ! -f "packages/$pkg/dist/index.mjs" ]; then
    echo "building $pkg ..."
    ( cd "packages/$pkg" && ../../node_modules/.bin/vite build ) || \
      echo "WARN: $pkg vite build returned non-zero (check dist/index.mjs)"
  fi
done

# Merge Deno's peer-dependency package variants to single instances (reflect-metadata,
# @nestjs/*, … keep global singleton state; two instances split it → DI / metadata
# failures at boot).
python3 deno-spike/dedup-packages.py

# Generate the full root + member deno.json import map (needs node_modules present so
# it can auto-resolve extensionless deep npm subpaths).
python3 deno-spike/gen-import-map.py

echo "done. Next: bash deno-spike/apply-patches.sh"
