#!/usr/bin/env bash
# Prepares the repo so `deno install` can resolve twenty-server's full npm dependency
# graph (the foundation for booting the real server on Deno). Two transforms are
# needed because Deno doesn't speak Yarn's dialect:
#
#   1. Scope `workspaces` to the server-needed packages. Deno walks every workspace
#      member, and twenty-front pulls `linkify-react@4.3.3`, whose published manifest
#      has a malformed requirement (`linkifyjs: "==4.3.3"`) that Deno's semver parser
#      rejects, aborting the whole install. The server doesn't use twenty-front.
#   2. Rewrite Yarn `patch:NAME@VER#file` specs to the exact `VER`. Deno can't parse
#      the `patch:` protocol; left as-is it resolves the wrong versions. After install
#      we re-apply the patches with apply-patches.sh (which needs the exact versions).
#
# This MUTATES package.json + packages/twenty-server/package.json (backed up to
# /tmp). It intentionally leaves them transformed so `deno run`/deploy also resolve
# the scoped graph — that is "deno build mode". Revert with:
#   git checkout package.json packages/twenty-server/package.json
#
# Known limitation: Deno ignores yarn.lock, so `^x-dev` ranges drift (e.g.
# @typescript/native-preview / tsgo resolves newer and breaks the nx BUILD toolchain).
# That only affects nx-based typecheck/test, not running the app — pin exact versions
# if you need the nx toolchain under Deno.
#
#   bash deno-spike/prepare-deno-deps.sh && bash deno-spike/apply-patches.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

cp package.json /tmp/twenty-root-package.json.deno-bak
cp packages/twenty-server/package.json /tmp/twenty-server-package.json.deno-bak
echo "backed up package.json files to /tmp/*.deno-bak"

python3 - <<'PY'
import json, re

SERVER_WORKSPACES = [
    'packages/twenty-server',
    'packages/twenty-shared',
    'packages/twenty-emails',
    'packages/twenty-client-sdk',
]

def depatch(deps):
    for name, spec in list(deps.items()):
        if isinstance(spec, str) and spec.startswith('patch:'):
            match = re.search(r'@([0-9][^@#]*)#', spec)
            if match:
                deps[name] = match.group(1)
                print(f'  de-patched {name}: -> {match.group(1)}')

root = json.load(open('package.json'))
root['workspaces'] = {'packages': SERVER_WORKSPACES}
for section in ('dependencies', 'devDependencies'):
    depatch(root.get(section, {}))
json.dump(root, open('package.json', 'w'), indent=2)
print('scoped workspaces ->', SERVER_WORKSPACES)

server = json.load(open('packages/twenty-server/package.json'))
for section in ('dependencies', 'devDependencies'):
    depatch(server.get(section, {}))
json.dump(server, open('packages/twenty-server/package.json', 'w'), indent=2)
PY

# Minimal ROOT deno.json so `deno install` links the workspace members (twenty-shared
# etc.). nodeModulesDir must live in the root deno.json (Deno warns on a member). The
# full import map is generated by gen-import-map.py AFTER install (it scans node_modules
# to auto-resolve extensionless deep subpaths).
cat > deno.json <<'JSON'
{
  "nodeModulesDir": "auto",
  "workspace": [
    "./packages/twenty-server",
    "./packages/twenty-shared",
    "./packages/twenty-emails",
    "./packages/twenty-client-sdk"
  ]
}
JSON

echo "running deno install ..."
deno install

# Node-style workspace symlinks. Deno's node_modules layout resolves workspace members
# its own way, but Node-based build tools (vite) need real node_modules/<pkg> symlinks
# (which Yarn would create). Without these, building twenty-emails fails on
# `Cannot find module 'twenty-shared/translations'`.
for pkg in twenty-shared twenty-emails twenty-client-sdk; do
  ln -sfn "../packages/$pkg" "node_modules/$pkg"
done

# Build the workspace packages that consumers resolve only via dist/ (their package
# exports point at dist). Runtime .mjs comes from vite; the tsgo .d.ts step may fail on
# the drifted toolchain but that's types-only and irrelevant to running the app.
for pkg in twenty-shared twenty-emails twenty-client-sdk; do
  if [ ! -f "packages/$pkg/dist/index.mjs" ]; then
    echo "building $pkg ..."
    ( cd "packages/$pkg" && ../../node_modules/.bin/vite build ) || \
      echo "WARN: $pkg vite build returned non-zero (check dist/index.mjs)"
  fi
done

# Merge Deno's peer-dependency package variants to single instances (reflect-metadata,
# @nestjs/*, … keep global singleton state; two instances split it → DI / metadata
# failures at boot).
python3 deno-spike/dedup-packages.py

# Generate the full root + member deno.json import map (needs node_modules present so
# it can auto-resolve extensionless deep npm subpaths).
python3 deno-spike/gen-import-map.py

echo "done. Next: bash deno-spike/apply-patches.sh"
